import { useState } from 'react'
import { Activity, BrainCircuit, Check, Clock3, Eye, GitBranch, Network, ShieldAlert, ShieldCheck, SlidersHorizontal, Sparkles } from 'lucide-react'
import { motion } from 'framer-motion'
import { api } from '../lib/api'

type Action = 'ALLOW' | 'STEP-UP VERIFICATION' | 'TEMPORARY HOLD' | 'BLOCK'
const modules = [
  { name: 'ML Fraud Classifier', icon: BrainCircuit, status: 'ONLINE', performance: '94.8%', signals: '128 signals', updated: '38 sec ago', tone: 'cyan' },
  { name: 'Behavioral Anomaly Detection', icon: Activity, status: 'LEARNING', performance: '91.3%', signals: '64 signals', updated: '2 min ago', tone: 'amber' },
  { name: 'Graph Intelligence', icon: Network, status: 'ONLINE', performance: '96.1%', signals: '2.4k links', updated: '1 min ago', tone: 'green' },
  { name: 'Adaptive Risk Engine', icon: SlidersHorizontal, status: 'ONLINE', performance: '99.2%', signals: '18 policies', updated: '12 sec ago', tone: 'blue' },
]
const scoreInputs = [{ label: 'ML Score', value: 92, tone: 'cyan' }, { label: 'Behavior Score', value: 88, tone: 'amber' }, { label: 'Anomaly Score', value: 95, tone: 'red' }, { label: 'Graph Score', value: 97, tone: 'purple' }]
const reasons = ['Unusual transaction velocity', 'Device linked to multiple accounts', 'Suspicious merchant relationship', 'Behavior differs significantly from historical baseline', 'Connected to high-risk network cluster']
const actionLabels: Action[] = ['ALLOW', 'STEP-UP VERIFICATION', 'TEMPORARY HOLD', 'BLOCK']

function ScoreBar({ label, value, tone }: { label: string; value: number; tone: string }) { return <div className="score-bar-row"><div><span>{label}</span><strong>{value}</strong></div><div className="score-bar"><i className={tone} style={{ width: `${value}%` }} /></div></div> }
function ModuleCard({ module }: { module: typeof modules[number] }) { const Icon = module.icon; return <div className="defense-module"><div className="module-top"><div className={`module-icon ${module.tone}`}><Icon size={17} /></div><span className={`module-status ${module.status.toLowerCase()}`}><i />{module.status}</span></div><h3>{module.name}</h3><div className="module-detail"><span>Detection performance</span><strong>{module.performance}</strong></div><div className="module-detail"><span>Signals analyzed</span><strong>{module.signals}</strong></div><div className="module-detail"><span>Last updated</span><strong>{module.updated}</strong></div></div> }

export default function BlueTeam() {
 const [action, setAction] = useState<Action>('BLOCK'); const [adapted, setAdapted] = useState(false); const [capability, setCapability] = useState(90.6)
 const scores = scoreInputs.map((score) => score.value); const finalRisk = Math.round(scores.reduce((total, value) => total + value, 0) / scores.length)
 const verdict = finalRisk <= 30 ? 'ALLOW' : finalRisk <= 60 ? 'VERIFY' : finalRisk <= 80 ? 'HOLD' : 'BLOCK'
 return <div className="blue-team-page"><div className="blue-heading"><div><p className="eyebrow">BLUE TEAM <span>•</span> Defense operations</p><h1>BLUE TEAM DEFENSE</h1><p className="subheading">Detect, explain and mitigate evolving payment fraud.</p></div><div className="defense-chip"><ShieldCheck size={16} /> Defense engine active</div></div>
  <section><div className="section-heading blue-section-heading"><div><p className="eyebrow">Defense stack</p><h2>Detection modules</h2></div><span className="threat-count">4 modules online</span></div><div className="defense-module-grid">{modules.map((module) => <ModuleCard key={module.name} module={module} />)}</div></section>
  <div className="risk-engine-grid"><section className="risk-engine glass-card"><div className="section-heading"><div><p className="eyebrow">Selected transaction · TXN-84921</p><h2>Risk Engine Visualization</h2></div><span className="synthetic-label"><Sparkles size={13} /> Deterministic demo</span></div><div className="risk-layout"><div className="risk-gauge"><div className="gauge-ring" style={{ '--risk-angle': `${finalRisk * 1.8}deg` } as React.CSSProperties}><div><strong>{finalRisk}</strong><span>FINAL RISK</span></div></div><b className={`risk-verdict ${verdict.toLowerCase()}`}>{verdict}</b></div><div className="score-list">{scoreInputs.map((score) => <ScoreBar key={score.label} {...score} />)}<div className="calculation-note"><GitBranch size={14} /> Final Risk = average of four explainable scores <strong>{finalRisk}</strong></div></div></div><div className="thresholds"><span><i className="allow" />0–30 Allow</span><span><i className="verify" />30–60 Verify</span><span><i className="hold" />60–80 Hold</span><span><i className="block" />80–100 Block</span></div></section><section className="risky-reasons glass-card"><div className="section-heading"><div><p className="eyebrow">Explainability layer</p><h2>Why this transaction is risky</h2></div><Eye size={16} color="#e5b257" /></div><div className="reason-list">{reasons.map((reason, index) => <motion.div key={reason} initial={{ opacity: 0, x: 8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .07 }}><ShieldAlert size={15} /><span>{reason}</span></motion.div>)}</div></section></div>
  <section className="mitigation-panel glass-card"><div><p className="eyebrow">Blue team response</p><h2>Mitigation decision</h2><p>Apply a local decision to the selected synthetic transaction.</p></div><div className="mitigation-actions">{actionLabels.map((item) => <button className={action === item ? 'active' : ''} key={item} onClick={() => setAction(item)}>{item === 'ALLOW' ? <Check size={15} /> : item === 'BLOCK' ? <ShieldAlert size={15} /> : item === 'TEMPORARY HOLD' ? <Clock3 size={15} /> : <ShieldCheck size={15} />}{item}</button>)}</div><div className="decision-status"><span>Current transaction state</span><strong>{action}</strong></div><button className={`adapt-button ${adapted ? 'active' : ''}`} onClick={() => { setAdapted(true); api.adaptDefense('DEFENSE BLIND SPOT').then((result) => setCapability(result.after_detection)) }}><Sparkles size={14} /> {adapted ? `DEFENSE ADAPTED · ${capability}%` : 'ADAPT TO DEFENSE BLIND SPOT'}</button></section>
 </div>
}
