import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowRight, Ban, Check, Clock3, CreditCard, MapPin, Radar, ShieldAlert, Smartphone, Wallet, X, Zap } from 'lucide-react'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api, type RiskAnalysis, type Transaction } from '../lib/api'

const attackCatalog = [
 ['Synthetic Identity', 'Forge a synthetic customer profile from inconsistent identity signals.', 'High', 'Fingerprint'], ['Account Takeover', 'Replay synthetic session patterns against protected account flows.', 'Critical', 'KeyRound'], ['Card Testing', 'Generate low-value authorization bursts across test instruments.', 'High', 'CreditCard'], ['Money Mule Network', 'Model coordinated account and merchant movement patterns.', 'Critical', 'Network'], ['Merchant Collusion', 'Simulate suspicious settlement relationships between entities.', 'High', 'Handshake'], ['Behavioral Mimicry', 'Reproduce a trusted customer rhythm with subtle deviations.', 'Medium', 'ScanFace'], ['Device Rotation', 'Rotate synthetic device identities across a controlled cluster.', 'Medium', 'Smartphone'], ['Refund Abuse', 'Create repeated refund loops with synthetic order histories.', 'High', 'Receipt'], ['Velocity Attack', 'Stress velocity controls with geographically distributed bursts.', 'Critical', 'Gauge'], ['Composite Attack', 'Combine multiple attack vectors into one evolving scenario.', 'Critical', 'Layers'],
]
const processSteps = ['Analyzing payment ecosystem', 'Selecting attack strategy', 'Creating synthetic entities', 'Generating transaction behavior', 'Testing Blue Team', 'Evaluating attack']
const recentAttacks = [['EV-0418', 'Velocity Attack', 'CRITICAL', '2m ago'], ['EV-0417', 'Behavioral Mimicry', 'MEDIUM', '18m ago'], ['EV-0416', 'Card Testing + Device Rotation', 'HIGH', '42m ago'], ['EV-0415', 'Merchant Collusion', 'HIGH', '1h ago']]

type Txn = { id: string; customer: string; merchant: string; amount: string; location: string; method: string; risk: number; status: 'BLOCKED' | 'VERIFY' | 'HOLD' | 'ALLOWED' }
const transactions: Txn[] = [
 { id: 'TXN-84921', customer: '#A81F', merchant: '#M921', amount: '₹12,840', location: 'Kolkata', method: 'UPI', risk: 94, status: 'BLOCKED' },
 { id: 'TXN-84920', customer: '#C44B', merchant: '#M104', amount: '₹2,499', location: 'Mumbai', method: 'Card', risk: 71, status: 'VERIFY' },
 { id: 'TXN-84919', customer: '#D90E', merchant: '#M772', amount: '₹48,200', location: 'Delhi', method: 'Net Banking', risk: 89, status: 'BLOCKED' },
 { id: 'TXN-84918', customer: '#F302', merchant: '#M318', amount: '₹1,280', location: 'Bengaluru', method: 'Wallet', risk: 22, status: 'ALLOWED' },
 { id: 'TXN-84917', customer: '#B73C', merchant: '#M442', amount: '₹8,750', location: 'Hyderabad', method: 'UPI', risk: 64, status: 'HOLD' },
]
const chartSets = { '24H': [{ t: '00', legit: 32, suspicious: 9, fraud: 3 }, { t: '04', legit: 45, suspicious: 12, fraud: 5 }, { t: '08', legit: 59, suspicious: 15, fraud: 7 }, { t: '12', legit: 52, suspicious: 13, fraud: 4 }, { t: '16', legit: 72, suspicious: 22, fraud: 9 }, { t: '20', legit: 64, suspicious: 18, fraud: 8 }, { t: 'Now', legit: 81, suspicious: 25, fraud: 11 }], '7D': [{ t: 'Mon', legit: 38, suspicious: 12, fraud: 4 }, { t: 'Tue', legit: 52, suspicious: 17, fraud: 6 }, { t: 'Wed', legit: 48, suspicious: 15, fraud: 5 }, { t: 'Thu', legit: 69, suspicious: 20, fraud: 8 }, { t: 'Fri', legit: 62, suspicious: 22, fraud: 9 }, { t: 'Sat', legit: 73, suspicious: 19, fraud: 7 }, { t: 'Sun', legit: 81, suspicious: 25, fraud: 11 }], '30D': [{ t: '01', legit: 31, suspicious: 8, fraud: 3 }, { t: '06', legit: 47, suspicious: 14, fraud: 4 }, { t: '11', legit: 55, suspicious: 16, fraud: 7 }, { t: '16', legit: 63, suspicious: 21, fraud: 8 }, { t: '21', legit: 71, suspicious: 19, fraud: 8 }, { t: '26', legit: 76, suspicious: 24, fraud: 10 }, { t: '30', legit: 81, suspicious: 25, fraud: 11 }] }

function Counter({ value }: { value: string }) { return <motion.span initial={{ opacity: 0, y: 7 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .45 }}>{value}</motion.span> }
function Metric({ label, value, icon: Icon, tone }: { label: string; value: string; icon: typeof CreditCard; tone: string }) { return <div className="command-metric"><div className={`command-metric-icon ${tone}`}><Icon size={16} /></div><span>{label}</span><strong><Counter value={value} /></strong></div> }
function Status({ status }: { status: Txn['status'] }) { return <span className={`txn-status ${status.toLowerCase()}`}><i />{status}</span> }
function toTxn(transaction: Transaction): Txn { return { id: transaction.id, customer: transaction.customer_id.replace('C-', '#'), merchant: transaction.merchant_id.replace('M-', '#'), amount: `₹${transaction.amount.toLocaleString('en-IN')}`, location: transaction.location, method: transaction.payment_method, risk: transaction.risk_score, status: transaction.status === 'ALLOWED' ? 'ALLOWED' : transaction.status === 'BLOCKED' ? 'BLOCKED' : transaction.status === 'VERIFY' ? 'VERIFY' : 'HOLD' } }

function DetailDrawer({ txn, close, update }: { txn: Txn; close: () => void; update: (status: Txn['status']) => void }) {
 const [analysis, setAnalysis] = useState<RiskAnalysis | null>(null); useEffect(() => { setAnalysis(null); api.risk(txn.id).then(setAnalysis) }, [txn.id]); const riskScore = analysis?.risk_score ?? txn.risk; const details = [['Transaction ID', txn.id], ['Amount', txn.amount], ['Customer', `Customer ${txn.customer}`], ['Merchant', `Merchant ${txn.merchant}`], ['Device', 'Pixel 8 · DVC-28A1'], ['Location', `${txn.location}, India`], ['Payment method', txn.method], ['Risk score', `${riskScore} / 100`], ['Fraud probability', `${riskScore > 80 ? '96.4' : riskScore > 50 ? '62.1' : '8.7'}%`], ['Behavior anomaly', riskScore > 80 ? 'Severe' : riskScore > 50 ? 'Elevated' : 'Normal'], ['Graph risk', riskScore > 80 ? 'Connected cluster' : 'Low exposure']]
 return <motion.aside className="detail-drawer" initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} transition={{ type: 'spring', damping: 25 }}><div className="drawer-header"><div><p className="eyebrow">Transaction review</p><h2>{txn.id}</h2></div><button className="drawer-close" onClick={close} aria-label="Close transaction details"><X size={18} /></button></div><div className="drawer-risk"><span>Risk score · {analysis?.classification ?? 'ANALYZING'}</span><strong>{riskScore}</strong><div className="risk-meter"><i style={{ width: `${riskScore}%` }} /></div></div><div className="detail-list">{details.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="flag-reasons"><h3>Why was this flagged?</h3>{(analysis?.reasons ?? ['Analyzing transaction signals...']).map((reason) => <p key={reason}><ShieldAlert size={15} /> {reason}</p>)}</div><div className="drawer-actions">{(['ALLOWED', 'VERIFY', 'HOLD', 'BLOCKED'] as Txn['status'][]).map((status) => <button key={status} className={status === txn.status ? 'selected' : ''} onClick={() => update(status)}>{status === 'ALLOWED' ? <Check size={14} /> : status === 'VERIFY' ? <ShieldAlert size={14} /> : status === 'HOLD' ? <Clock3 size={14} /> : <Ban size={14} />}{status === 'ALLOWED' ? 'ALLOW' : status === 'BLOCKED' ? 'BLOCK' : status}</button>)}</div></motion.aside>
}

export default function Dashboard({ navigate }: { navigate: (path: string) => void }) {
 const [tab, setTab] = useState<keyof typeof chartSets>('24H'); const [selected, setSelected] = useState<Txn | null>(null); const [rows, setRows] = useState(transactions); const [attack, setAttack] = useState(attackCatalog[0]); const [processStep, setProcessStep] = useState(-1); const [generated, setGenerated] = useState(false); const [generation, setGeneration] = useState(1); const [generatedId, setGeneratedId] = useState('EV-0421')
 useEffect(() => { Promise.all([api.transactions(), api.attacks(), api.incidents()]).then(([remoteTransactions]) => setRows(remoteTransactions.map(toTxn))) }, [])
 const updateStatus = (status: Txn['status']) => { if (!selected) return; setRows(rows.map((row) => row.id === selected.id ? { ...row, status } : row)); setSelected({ ...selected, status }); void api.action(selected.id, status === 'ALLOWED' ? 'ALLOW' : status === 'BLOCKED' ? 'BLOCK' : status) }
 const generateAttack = () => { setGenerated(false); setProcessStep(0); let step = 0; const timer = window.setInterval(() => { step += 1; if (step >= processSteps.length) { window.clearInterval(timer); api.generateAttack(attack[0]).then((result) => setGeneratedId(result.id)); setGenerated(true); setProcessStep(-1) } else setProcessStep(step) }, 430) }
 const evolveAttack = () => { setGeneration((current) => Math.min(current + 1, 3)); setGenerated(true); void api.evolveAttack(generatedId) }
 const evolvedName = generation === 1 ? 'Synthetic Identity' : generation === 2 ? 'Synthetic Identity + Device Rotation' : 'Synthetic Identity + Device Rotation + Mule Network'
 return <div className="command-center"><div className="command-heading"><div><p className="eyebrow">RED TEAM LAB <span>•</span> Synthetic environment</p><h1>RED TEAM LAB</h1><p className="subheading">Stress-test the payment defense with evolving synthetic attacks.</p></div><button className="simulation-cta" onClick={() => navigate('/simulation')}><Zap size={16} /> Launch adversarial simulation <ArrowRight size={15} /></button></div>
    <section className="lab-generator glass-card"><div className="generator-copy"><p className="eyebrow">Controlled attack generation</p><h2>Generate novel attack</h2><p>Every scenario is synthetic and isolated. Select a strategy, then observe how the defense responds.</p><div className="attack-select"><span>Selected strategy</span><strong>{attack[0]}</strong></div><button className="novel-button" onClick={generateAttack}><Zap size={18} /> GENERATE NOVEL ATTACK</button></div><div className="generator-visual"><div className="lab-core"><Radar size={30} /><span>LAB<br />CORE</span></div><div className="lab-ring ring-a" /><div className="lab-ring ring-b" /></div>{processStep >= 0 && <div className="process-panel"><span className="process-label">Synthetic generation in progress</span>{processSteps.map((step, index) => <div className={`process-step ${index < processStep ? 'done' : ''} ${index === processStep ? 'current' : ''}`} key={step}><i>{index < processStep ? '✓' : index + 1}</i>{step}{index === processStep && <span className="process-loader" />}</div>)}</div>}{generated && <div className="generated-attack"><div><p className="eyebrow">ATTACK EV-0421</p><h3>{evolvedName}</h3></div><span className="severity-critical">CRITICAL</span><div className="generated-stats"><span><b>18</b>Accounts</span><span><b>7</b>Devices</span><span><b>12</b>Merchants</span><span><b>2,431</b>Transactions</span><span><b>17 days</b>Duration</span><span><b>₹24.8L</b>Estimated Exposure</span><span><b>31%</b>Detection Probability</span></div><div className="generated-footer"><span>UNDER SIMULATION</span><button className="evolve-button" onClick={evolveAttack}><Zap size={14} /> EVOLVE ATTACK</button></div></div>}</section>
    <div className="lab-section-heading"><div><p className="eyebrow">Adversarial library</p><h2>Attack strategies</h2></div><span>10 synthetic scenarios</span></div><div className="attack-grid">{attackCatalog.map((item) => <button className={`attack-card ${attack[0] === item[0] ? 'selected' : ''}`} key={item[0]} onClick={() => setAttack(item)}><div className="attack-card-top"><div className="attack-icon"><Zap size={16} /></div><span className={`severity-${item[2].toLowerCase()}`}>{item[2]}</span></div><h3>{item[0]}</h3><p>{item[1]}</p><span className="simulate-link">Simulate <ArrowRight size={13} /></span></button>)}</div>
    <div className="red-team-lower"><section className="recent-attacks glass-card"><div className="section-heading"><div><p className="eyebrow">Synthetic activity</p><h2>Recent Red Team Attacks</h2></div><span className="threat-count">Local demo history</span></div>{recentAttacks.map((item) => <div className="recent-attack" key={item[0]}><span className="recent-id">{item[0]}</span><strong>{item[1]}</strong><span className={`severity-${item[2].toLowerCase()}`}>{item[2]}</span><time>{item[3]}</time></div>)}</section><section className="evolution-card glass-card"><div className="section-heading"><div><p className="eyebrow">Attack lineage</p><h2>Evolution path</h2></div><Zap size={16} color="#e4b258" /></div><div className="generation-list">{['Synthetic Identity', 'Synthetic Identity + Device Rotation', 'Synthetic Identity + Device Rotation + Mule Network'].map((name, index) => <div className={`generation ${generation === index + 1 ? 'current' : ''}`} key={name}><span>Generation {index + 1}</span><strong>{name}</strong>{generation === index + 1 && <i>Current</i>}</div>)}</div></section></div>
  <div className="command-metrics"><Metric label="Transactions monitored" value="1,284,392" icon={CreditCard} tone="cyan" /><Metric label="Active threats" value="27" icon={ShieldAlert} tone="red" /><Metric label="Attacks simulated" value="8,421" icon={Zap} tone="amber" /><Metric label="Detection rate" value="94.8%" icon={Check} tone="green" /><Metric label="False positive rate" value="1.7%" icon={ShieldAlert} tone="blue" /><Metric label="Average detection time" value="1.8s" icon={Clock3} tone="purple" /></div>
  <div className="command-main-grid"><section className="threat-chart glass-card"><div className="section-heading"><div><p className="eyebrow">Threat telemetry</p><h2>Threat Activity</h2></div><div className="chart-tabs">{(['24H', '7D', '30D'] as const).map((item) => <button className={tab === item ? 'active' : ''} key={item} onClick={() => setTab(item)}>{item}</button>)}</div></div><div className="chart-legend command-legend"><span><i className="dot legit" />Legitimate Transactions</span><span><i className="dot suspicious" />Suspicious Transactions</span><span><i className="dot fraud" />Confirmed Fraud</span></div><div className="large-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartSets[tab]}><defs><linearGradient id="legitFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4bd6d7" stopOpacity={.22} /><stop offset="100%" stopColor="#4bd6d7" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="t" axisLine={false} tickLine={false} tick={{ fill: '#6f8296', fontSize: 11 }} /><YAxis hide /><Tooltip contentStyle={{ background: '#101e30', border: '1px solid #294056', borderRadius: 7, color: '#fff' }} /><Area type="monotone" dataKey="legit" stroke="#4bd6d7" strokeWidth={2} fill="url(#legitFill)" /><Area type="monotone" dataKey="suspicious" stroke="#e4b258" strokeWidth={2} fill="none" /><Area type="monotone" dataKey="fraud" stroke="#ef6f76" strokeWidth={2} fill="none" /></AreaChart></ResponsiveContainer></div></section><section className="live-threats glass-card"><div className="section-heading"><div><p className="eyebrow">Blue team watchlist</p><h2>Live Threats</h2></div><span className="threat-count">27 active</span></div><div className="threat-item critical"><div><b>Critical</b><strong>Coordinated Mule Network</strong><small>12 linked entities · 3 regions</small></div><ArrowRight size={15} /></div><div className="threat-item high"><div><b>High</b><strong>Synthetic Identity</strong><small>8 accounts · shared device graph</small></div><ArrowRight size={15} /></div><div className="threat-item medium"><div><b>Medium</b><strong>Behavioral Anomaly</strong><small>Unusual checkout sequence</small></div><ArrowRight size={15} /></div></section></div>
  <section className="stream-card glass-card"><div className="stream-head"><div><p className="eyebrow">Live feed <span className="pulse-dot" /></p><h2>Live Transaction Stream</h2></div><span className="stream-rate"><span className="pulse-dot" /> 4,280 events / min</span></div><div className="transaction-table"><div className="transaction-header"><span>Transaction ID</span><span>Customer</span><span>Merchant</span><span>Amount</span><span>Location</span><span>Risk</span><span>Status</span></div><AnimatePresence initial={false}>{rows.map((txn) => <motion.button layout key={txn.id} className="transaction-row" onClick={() => setSelected(txn)} initial={{ opacity: 0, x: -12 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .3 }}><span className="txn-id">{txn.id}</span><span>{txn.customer}</span><span>{txn.merchant}</span><span className="amount">{txn.amount}</span><span className="location"><MapPin size={12} />{txn.location}</span><span><b className={`risk-number ${txn.risk > 80 ? 'high-risk' : txn.risk > 50 ? 'mid-risk' : 'low-risk'}`}>{txn.risk}</b></span><Status status={txn.status} /></motion.button>)}</AnimatePresence></div></section>
  <div className="stream-note"><Wallet size={14} /> Demo data stream · UPI, Card, Wallet, and Net Banking events <span>Click a transaction to investigate</span></div>
  <AnimatePresence>{selected && <><motion.div className="drawer-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelected(null)} /><DetailDrawer txn={selected} close={() => setSelected(null)} update={updateStatus} /></>}</AnimatePresence>
 </div>
}
