import { useEffect, useState } from 'react'
import { ArrowRight, Radar, Zap } from 'lucide-react'
import { api, type Attack } from '../lib/api'

const attackCatalog = [
  ['Synthetic Identity', 'Forge a synthetic customer profile from inconsistent identity signals.', 'High'], ['Account Takeover', 'Replay synthetic session patterns against account flows.', 'Critical'], ['Card Testing', 'Generate low-value authorization bursts across test instruments.', 'High'], ['Money Mule Network', 'Model coordinated account and merchant movement patterns.', 'Critical'], ['Merchant Collusion', 'Simulate suspicious settlement relationships between entities.', 'High'], ['Behavioral Mimicry', 'Reproduce a customer rhythm with controlled deviations.', 'Medium'], ['Device Rotation', 'Rotate synthetic device identities across a controlled cluster.', 'Medium'], ['Refund Abuse', 'Create refund loops with synthetic order histories.', 'High'], ['Velocity Attack', 'Stress velocity controls with distributed bursts.', 'Critical'], ['Composite Attack', 'Combine multiple configured attack vectors.', 'Critical'],
]

export default function Dashboard({ navigate }: { navigate: (path: string) => void }) {
  const [selected, setSelected] = useState(attackCatalog[0])
  const [attacks, setAttacks] = useState<Attack[]>([])
  const [generated, setGenerated] = useState<Attack | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const load = () => api.attacks().then(setAttacks).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false))
  useEffect(() => { void load() }, [])
  const generate = () => { setError(null); setLoading(true); api.generateAttack(selected[0]).then((result) => { setGenerated(result); setAttacks((current) => [result, ...current]) }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }
  const evolve = () => { if (!generated) return; setLoading(true); api.evolveAttack(generated.id).then((result) => { setGenerated(result); setAttacks((current) => current.map((item) => item.id === result.id ? result : item)) }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }
  return <div className="command-center"><div className="command-heading"><div><p className="eyebrow">RED TEAM LAB · Synthetic environment</p><h1>RED TEAM LAB</h1><p className="subheading">Generate controlled scenarios; every displayed result comes from the simulation API.</p></div><button className="simulation-cta" onClick={() => navigate('/simulation')}><Zap size={16} /> Open simulator <ArrowRight size={15} /></button></div>
    <section className="lab-generator glass-card"><div className="generator-copy"><p className="eyebrow">Controlled attack generation</p><h2>Generate synthetic attack</h2><p>Select a configured scenario and store its measured simulation parameters.</p><div className="attack-select"><span>Selected strategy</span><strong>{selected[0]}</strong></div><button className="novel-button" disabled={loading} onClick={generate}><Zap size={18} /> {loading ? 'WORKING…' : 'GENERATE ATTACK'}</button></div><div className="generator-visual"><div className="lab-core"><Radar size={30} /><span>LAB<br />CORE</span></div><div className="lab-ring ring-a" /><div className="lab-ring ring-b" /></div>{generated && <div className="generated-attack"><div><p className="eyebrow">SYNTHETIC · {generated.id}</p><h3>{generated.name}</h3></div><span className={`severity-${generated.severity.toLowerCase()}`}>{generated.severity}</span><div className="generated-stats"><span><b>{generated.accounts}</b>Accounts</span><span><b>{generated.devices}</b>Devices</span><span><b>{generated.merchants}</b>Merchants</span><span><b>{generated.transactions}</b>Transactions</span><span><b>{generated.detection_score ?? 'Not evaluated'}{generated.detection_score == null ? '' : ' / 100'}</b>Heuristic detection score</span><span><b>{generated.generation ?? 1}</b>Generation</span></div><div className="generated-footer"><span>{generated.status}</span><button className="evolve-button" onClick={evolve}><Zap size={14} /> EVOLVE ATTACK</button></div></div>}</section>
    {error && <div className="error-state" style={{ padding: 20 }}>{error}</div>}
    <div className="lab-section-heading"><div><p className="eyebrow">Controlled configuration</p><h2>Attack strategies</h2></div><span>{attackCatalog.length} synthetic scenarios</span></div><div className="attack-grid">{attackCatalog.map((item) => <button className={`attack-card ${selected[0] === item[0] ? 'selected' : ''}`} key={item[0]} onClick={() => setSelected(item)}><div className="attack-card-top"><div className="attack-icon"><Zap size={16} /></div><span className={`severity-${item[2].toLowerCase()}`}>{item[2]}</span></div><h3>{item[0]}</h3><p>{item[1]}</p><span className="simulate-link">Select <ArrowRight size={13} /></span></button>)}</div>
    <section className="recent-attacks glass-card"><div className="section-heading"><div><p className="eyebrow">Stored synthetic records</p><h2>Recent Red Team Attacks</h2></div><span className="threat-count">{attacks.length} recorded</span></div>{attacks.map((item) => <div className="recent-attack" key={item.id}><span className="recent-id">{item.id}</span><strong>{item.name}</strong><span className={`severity-${item.severity.toLowerCase()}`}>{item.severity}</span><time>{new Date(item.created_at).toLocaleString()}</time></div>)}{!attacks.length && !loading && <div className="empty-state">No attacks have been generated.</div>}</section>
  </div>
}
