import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, BrainCircuit, Check, CircleDot, Clock3, Crosshair, Play, RotateCcw, ShieldAlert, ShieldCheck, Target, Zap } from 'lucide-react'
import { AnimatePresence, motion } from 'framer-motion'

const stages = [
 ['STAGE 1', 'Normal payment activity', 'Baseline traffic is stable across the synthetic network.'], ['STAGE 2', 'Red Team selects attack', 'Adversarial strategy: Synthetic Identity + Device Rotation.'], ['STAGE 3', 'Synthetic accounts are created', '18 test accounts are provisioned in the isolated arena.'], ['STAGE 4', 'Suspicious transaction behavior begins', 'Velocity and checkout patterns begin to diverge.'], ['STAGE 5', 'Attack spreads through payment network', 'Suspicious relationships propagate across the entity graph.'], ['STAGE 6', 'Blue Team detects anomalies', 'Behavior and graph signals move above alert thresholds.'], ['STAGE 7', 'Risk score increases', 'Risk engine recalculates the transaction cluster at 76.'], ['STAGE 8', 'Transaction is blocked', 'High-confidence fraud is blocked by the adaptive risk engine.'], ['STAGE 9', 'Red Team evolves attack', 'A novel relationship pattern is introduced.'], ['STAGE 10', 'Blue Team adapts', 'Detection policy updates against the new synthetic pattern.'], ['STAGE 11', 'Attack is contained', 'All synthetic entities are isolated and the arena is stable.'],
] as const
const events = [['16:42:01', 'Synthetic account created', 'red'], ['16:42:04', 'Transaction velocity anomaly detected', 'blue'], ['16:42:06', 'Device relationship anomaly detected', 'blue'], ['16:42:08', 'Risk score: 76', 'amber'], ['16:42:09', 'Transaction blocked', 'blue'], ['16:42:11', 'Red Team evolving attack', 'red'], ['16:42:15', 'New pattern discovered', 'amber'], ['16:42:20', 'Blue Team adapting', 'blue'], ['16:42:26', 'Attack contained', 'green']]
const metrics = [['Attacks Generated', '32', 'red'], ['Successful Evasions', '3', 'amber'], ['Novel Patterns', '2', 'purple']]
const blueMetrics = [['Attacks Detected', '29'], ['Detection Rate', '90.6%'], ['False Positives', '1.7%'], ['Average Response Time', '1.8s']]

export default function Simulation() {
 const [running, setRunning] = useState(false); const [stage, setStage] = useState(-1); const [complete, setComplete] = useState(false); const [elapsed, setElapsed] = useState(0)
 useEffect(() => { if (!running) return; const timer = window.setInterval(() => { setElapsed((value) => value + 1); setStage((value) => { if (value >= stages.length - 1) { window.clearInterval(timer); setRunning(false); setComplete(true); return value } return value + 1 }) }, 3000); return () => window.clearInterval(timer) }, [running])
 const launch = () => { setStage(0); setElapsed(0); setComplete(false); setRunning(true) }; const progress = stage < 0 ? 0 : ((stage + (running ? Math.min(elapsed / 3, .95) : 1)) / stages.length) * 100
 const currentEvents = useMemo(() => events.filter((_, index) => complete || index <= Math.max(0, stage - 1)), [stage, complete])
 return <div className="simulation-page"><div className="arena-heading"><div><p className="eyebrow">EVOPAY AI <span>•</span> Controlled synthetic environment</p><h1>ADVERSARIAL ARENA</h1><p className="subheading">Red Team vs Blue Team</p></div><div className="arena-safety"><ShieldCheck size={15} /> No real payment systems connected</div></div>
  <section className="arena-hero glass-card"><div className="arena-intro"><span className="arena-kicker">{running ? `SIMULATION ACTIVE · ${Math.min(stage + 1, stages.length)} / ${stages.length}` : complete ? 'SIMULATION COMPLETE' : 'READY TO RUN'}</span><h2>{running ? stages[stage][1] : complete ? 'BLUE TEAM ADAPTED' : 'Test the limits of the defense.'}</h2><p>{running ? stages[stage][2] : complete ? 'The defense adapted to the novel pattern and contained the synthetic attack.' : 'Launch a deterministic adversarial sequence and watch the defense respond in real time.'}</p>{!running && <button className="launch-button" onClick={launch}>{complete ? <RotateCcw size={17} /> : <Play size={17} />}{complete ? 'REPLAY SIMULATION' : 'LAUNCH SIMULATION'} <ArrowRight size={15} /></button>}</div><div className="arena-core"><div className={`arena-orbit orbit-red ${running ? 'active' : ''}`} /><div className={`arena-orbit orbit-blue ${running ? 'active' : ''}`} /><div className="arena-versus"><span>RED TEAM</span><strong>VS</strong><span>BLUE TEAM</span></div><div className="arena-core-mark"><Crosshair size={22} /></div></div><div className="arena-progress"><div><span>Sequence progress</span><strong>{Math.round(progress)}%</strong></div><div className="arena-progress-bar"><i style={{ width: `${progress}%` }} /></div></div></section>
  <div className="arena-grid"><section className="team-panel red-team-panel glass-card"><div className="team-title"><div className="team-icon red"><Target size={17} /></div><div><p className="eyebrow">Adversarial force</p><h2>RED TEAM</h2></div><span className="team-live red">{running ? 'ACTIVE' : 'STANDBY'}</span></div><div className="team-metrics">{metrics.map(([label, value, tone]) => <div key={label}><span>{label}</span><strong className={tone}>{value}</strong></div>)}</div><div className="team-foot"><Zap size={13} /> Synthetic strategy mutation enabled</div></section><section className="team-panel blue-team-panel glass-card"><div className="team-title"><div className="team-icon blue"><ShieldCheck size={17} /></div><div><p className="eyebrow">Adaptive defense</p><h2>BLUE TEAM</h2></div><span className="team-live blue">{complete ? 'ADAPTED' : 'READY'}</span></div><div className="team-metrics">{blueMetrics.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="team-foot"><BrainCircuit size={13} /> Policy learning remains local to this run</div></section></div>
  <div className="simulation-body"><section className="stage-list glass-card"><div className="section-heading"><div><p className="eyebrow">Arena sequence</p><h2>Simulation stages</h2></div><span className="threat-count">{stages.length} stages</span></div>{stages.map(([number, title, description], index) => <motion.div className={`stage-row ${index === stage ? 'current' : ''} ${index < stage || complete ? 'done' : ''}`} key={number} initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .025 }}><span className="stage-number">{index < stage || complete ? <Check size={12} /> : number}</span><div><strong>{title}</strong><small>{description}</small></div>{index === stage && running && <span className="stage-pulse" />}</motion.div>)}</section><section className="event-timeline glass-card"><div className="section-heading"><div><p className="eyebrow">Live event timeline</p><h2>Signal chronology</h2></div><span className="timeline-clock"><Clock3 size={13} /> {running ? 'Streaming' : complete ? 'Final state' : 'Awaiting launch'}</span></div><div className="timeline-list">{currentEvents.map(([time, event, tone]) => <motion.div className="timeline-event" key={time} initial={{ opacity: 0, y: 7 }} animate={{ opacity: 1, y: 0 }}><time>{time}</time><i className={tone} /><span>{event}</span></motion.div>)}{!currentEvents.length && <div className="timeline-empty"><CircleDot size={20} /><span>Launch the arena to stream synthetic events.</span></div>}</div></section></div>
  <AnimatePresence>{complete && <motion.section className="complete-summary glass-card" initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }}><div className="complete-title"><div className="complete-icon"><Check size={20} /></div><div><p className="eyebrow">Run EV-SIM-0421</p><h2>SIMULATION COMPLETE</h2><strong>BLUE TEAM ADAPTED</strong></div></div><div className="complete-stats"><span><b>32</b>Attacks generated</span><span><b>29</b>Detected</span><span><b>3</b>Evasions</span><span><b>72</b>Transactions blocked</span><span><b>481</b>Accounts protected</span><span><b>2</b>Novel patterns discovered</span></div><div className="adapted-score"><span>Simulated detection score</span><strong>90.6% <small>↑ 4.8%</small></strong></div></motion.section>}</AnimatePresence>
 </div>
}
